init:
	composer install
	php artisan key:generate
	nano .env
	php artisan migrate:fresh --seed
	php artisan serve
git-Gabriella:
	git config --global user.name "GabriellaBatista"
	git config --global user.email "Gabriella10batista@gmail.com"
git-MariaEduarda:
	git config --global user.name "Eduarda19"
	git config --global user.email "Mariaeduardaj585@gmail.com"
git-MariaConceicao:
	git config --global user.name "Maria617"
	git config --global user.email "Mariac4682@gmail.com"
